[book]
authors = ["Lukas Wirth"]
language = "en"
multilingual = false
src = "src"
title = "The Little Book of Rust Macros"

[build]
create-missing = true
build-dir = "book"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/veykril/tlborm/"
# unfortunately the "Source Code Pro" font doesn't seem to work well with box characters
additional-css = ["res/code-font-patch.css"]