[book]
authors = ["Lukas Wirth"]
language = "en"
multilingual = false
src = "src"
title = "The Little Book of Rust Macros"
edition = "2018"

[build]
create-missing = true
build-dir = "book"

[output.linkcheck]
traverse-parent-directories = false
optional = true

[output.html]
default-theme = "ayu"
site-url = "/tlborm/"
mathjax-support = true
git-repository-url = "https://github.com/veykril/tlborm/"
additional-css = ["res/rust-syntax-bg-highlight.css"]

[output.html.redirect]
"/building-blocks/abacus-counting.html" = "../macros/building-blocks/abacus-counting.html"
"/building-blocks/ast-coercion.html" = "../macros/building-blocks/ast-coercion.html"
"/building-blocks/counting.html" = "../macros/building-blocks/counting.html"
"/building-blocks/parsing.html" = "../macros/building-blocks/parsing.html"

"/macros-practical.html" = "./macros/macros-practical.html"
"/patterns.html" = "./macros/patterns.html"
"/building-blocks.html" = "./macros/building-blocks.html"

"/patterns/callbacks.html" = "../macros/patterns/callbacks.html"
"/patterns/internal-rules.html" = "../macros/patterns/internal-rules.html"
"/patterns/push-down-acc.html" = "../macros/patterns/push-down-acc.html"
"/patterns/repetition-placement.html" = "../macros/patterns/repetition-placement.html"
"/patterns/tt-bundling.html" = "../macros/patterns/tt-bundling.html"
"/patterns/tt-muncher.html" = "../macros/patterns/tt-muncher.html"

"/macros/syntax/ast.html" = "../../syntax-extensions/ast.html"
"/macros/syntax/expansion.html" = "../../syntax-extensions/expansion.html"
"/macros/syntax/source-analysis.html" = "../../syntax-extensions/source-analysis.html"
